steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-northeast1-docker.pkg.dev/teachercan-436815/be_teachercan_2/teachercan-be-new',
      '.'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'teachercan-be-new',
      '--image', 'asia-northeast1-docker.pkg.dev/teachercan-436815/be_teachercan_2/teachercan-be-new',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
