steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/teachercan-436815/cloud-run-source-deploy/be_teachercan_2/back-end-teachercan-main:$COMMIT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-northeast1-docker.pkg.dev/teachercan-436815/cloud-run-source-deploy/be_teachercan_2/back-end-teachercan-main:$COMMIT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - back-end-teachercan-main
      - '--image=asia-northeast1-docker.pkg.dev/teachercan-436815/cloud-run-source-deploy/be_teachercan_2/back-end-teachercan-main:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--quiet'
options:
  logging: CLOUD_LOGGING_ONLY
