version: '3'

services:
  app:
    build: .
    image: teacher-can:latest
    ports:
      - "80:80"
      - "443:443"
      - "5000:3000"
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # 인증서 파일 위치