name: Deploy to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: 🔐 Store AES_KEY to Secret Manager
        run: |
          echo -n "${{ secrets.AES_KEY }}" | gcloud secrets create aes-key-prod \
            --data-file=- --replication-policy="automatic" || \
          echo -n "${{ secrets.AES_KEY }}" | gcloud secrets versions add aes-key-prod --data-file=-

      - name: 🛠️ Connect Secret to Cloud Run
        run: |
          gcloud run services update teachercan-be-new \
            --region=asia-northeast1 \
            --update-secrets=AES_KEY=aes-key-prod:latest
