name: Deploy to Production Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Production Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-app:latest

      - name: Deploy to GCP (Production)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            CONTAINER_NAME="nginx-app"
            PORT_MAPPING="80:80"
            ENV_PATH="/opt/app"
            USE_SSL=true

            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-app:latest

            sudo mkdir -p $ENV_PATH
            sudo bash -c "cat > $ENV_PATH/.env << EOL
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            LOCAL=false
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}
            SITE_URL=${{ secrets.SITE_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_URL=${{ secrets.OPENAI_URL }}
            LLM_MODEL=${{ secrets.LLM_MODEL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            AES_KEY=${{ secrets.AES_KEY }}
            EOL"

            sudo mkdir -p $ENV_PATH/ssl

            if sudo cp /etc/letsencrypt/live/api.teachercan.com/fullchain.pem $ENV_PATH/ssl/ && \
               sudo cp /etc/letsencrypt/live/api.teachercan.com/privkey.pem $ENV_PATH/ssl/; then
              sudo chmod 644 $ENV_PATH/ssl/fullchain.pem
              sudo chmod 600 $ENV_PATH/ssl/privkey.pem
              sudo chown $(whoami):$(whoami) $ENV_PATH/ssl/fullchain.pem
              sudo chown $(whoami):$(whoami) $ENV_PATH/ssl/privkey.pem

              docker run -d \
                --name $CONTAINER_NAME \
                -p $PORT_MAPPING \
                -p 443:443 \
                --env-file $ENV_PATH/.env \
                -v $ENV_PATH/ssl:/etc/nginx/ssl:ro \
                --restart always \
                ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-app:latest
            else
              echo "ERROR: SSL certificates not found!"
              exit 1
            fi

            docker image prune -a -f
